protected/modules/admin/controllers/DefaultController.php
<?php

class DefaultController extends Controller {
    public $pageHeading1;
    public $pageHeading2;

    public function actionIndex() {
        //$this->layout="main";
        if (Yii::app()->user->isGuest) {
            //$this->render('index');
            $this->redirect(Yii::app()->createUrl('default/login'));
        } else {
            $this->render('index');
        }
    }

    public function actionLogin() {
        $this->layout = "layout_login_admin";
        if (!Yii::app()->user->isGuest) {
            $this->redirect(Yii::app()->getModule('admin')->user->returnUrl);
        } else {
            $model = new LoginForm;
            // if it is ajax validation request
            if (isset($_POST['ajax']) && $_POST['ajax'] === 'login-form') {
                echo CActiveForm::validate($model);
                Yii::app()->end();
            }

            // collect user input data
            if (isset($_POST['LoginForm'])) {
                $model->attributes = $_POST['LoginForm'];
                // validate user input and redirect to the previous page if valid
                if ($model->validate() && $model->login())
                //$this->redirect(Yii::app()->getModule('admin')->user->returnUrl);
                    $this->redirect(Yii::app()->createUrl('/admin/default/index'));
            }
            // display the login form
            $this->render('login', array('model' => $model));
        }
    }

    public function actionRegister() {
        $this->pageTitle = Yii::app()->name . ' - Registration';
        $this->pageHeading1 = 'Registration';
        $this->pageHeading2 = 'Enter your credentials below';
        $this->layout = "layout_login_admin";
        if (Yii::app()->user->isGuest) {

            $model = new RegisterForm;


            if (isset($_POST['RegisterForm'])) {
                $newUser = new User;
                $model->attributes = $_POST['RegisterForm'];
                $newUser->attributes = $model->attributes;
                $newUser->password = md5($model->password);
                $newUser->isactive = 'yes';
                $newUser->createdon = new CDbExpression('NOW()');

                if ($model->validate()) {
                    if ($newUser->save()) {
                        $message = 'Registration Completed Successfully. Login To CMS ' . CHtml::link('Click Here', array('default/login'));
                        Yii::app()->user->setFlash('register', $message);
                        $this->refresh();
                    } else {
                        $message = 'There is some problem while registration. Please try again';
                        Yii::app()->user->setFlash('registererror', $message);
                        $this->refresh();
                    }
                }
            }

            // display the register form
            $this->render('register', array('model' => $model));
        } else {
            $this->redirect(Yii::app()->getModule('admin')->user->returnUrl);
        }
    }
  public function actionError(){ 
		if($error=Yii::app()->errorHandler->error)
		{
			if(Yii::app()->request->isAjaxRequest)
				echo $error['message'];
			else
				$this->render('error', $error);
		}
	}
    public function actionLogout() {

        Yii::app()->user->logout(false);

        $this->redirect(Yii::app()->getModule('admin')->user->loginUrl);
    }

}

protected/modules/admin/controllers/GoodsController.php
<?php
class GoodsController extends MYAdminController{
public $layout='//layouts/column2';

public function filters() {
        return array(
            //'accessControl', 
            'rights',
        );
    } 
public function actionView($id)
{
$this->render('view',array(
'model'=>$this->loadModel($id),
));
}

public function actionCreate()
{
$model=new Goods;

// Uncomment the following line if AJAX validation is needed
// $this->performAjaxValidation($model);

if(isset($_POST['Goods']))
{
$model->attributes=$_POST['Goods'];
if($model->save())
$this->redirect(array('view','id'=>$model->id));
}

$this->render('create',array(
'model'=>$model,
));
}

/**
* Updates a particular model.
* If update is successful, the browser will be redirected to the 'view' page.
* @param integer $id the ID of the model to be updated
*/
public function actionUpdate($id)
{
$model=$this->loadModel($id);

// Uncomment the following line if AJAX validation is needed
// $this->performAjaxValidation($model);

if(isset($_POST['Goods']))
{
$model->attributes=$_POST['Goods'];
if($model->save())
$this->redirect(array('view','id'=>$model->id));
}

$this->render('update',array(
'model'=>$model,
));
}

/**
* Deletes a particular model.
* If deletion is successful, the browser will be redirected to the 'admin' page.
* @param integer $id the ID of the model to be deleted
*/
public function actionDelete($id)
{
if(Yii::app()->request->isPostRequest)
{
// we only allow deletion via POST request
$this->loadModel($id)->delete();

// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
if(!isset($_GET['ajax']))
$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
}
else
throw new CHttpException(400,'Invalid request. Please do not repeat this request again.');
}

/**
* Lists all models.
*/
public function actionIndex()
{
$dataProvider=new CActiveDataProvider('Goods');
$this->render('index',array(
'dataProvider'=>$dataProvider,
));
}

/**
* Manages all models.
*/
public function actionAdmin()
{
$model=new Goods('search');
$model->unsetAttributes();  // clear any default values
if(isset($_GET['Goods']))
$model->attributes=$_GET['Goods'];

$this->render('admin',array(
'model'=>$model,
));
}

/**
* Returns the data model based on the primary key given in the GET variable.
* If the data model is not found, an HTTP exception will be raised.
* @param integer the ID of the model to be loaded
*/
public function loadModel($id)
{
$model=Goods::model()->findByPk($id);
if($model===null)
throw new CHttpException(404,'The requested page does not exist.');
return $model;
}

/**
* Performs the AJAX validation.
* @param CModel the model to be validated
*/
protected function performAjaxValidation($model)
{
if(isset($_POST['ajax']) && $_POST['ajax']==='goods-form')
{
echo CActiveForm::validate($model);
Yii::app()->end();
}
}
}

protected/modules/admin/controllers/PageController.php
<?php

class PageController extends MYAdminController{
	public $layout='main';

	public function filters()
	{
		return array(
			'rights', // perform access control for CRUD operations
		);
	}
 
	public function actionView($id)
	{
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new Page;
		$model->isactive='yes';

		// Uncomment the following line if AJAX validation is needed
		$this->performAjaxValidation($model);

		if(isset($_POST['Page']))
		{
			$model->attributes=$_POST['Page'];
			$model->isactive=$_POST['Page']['isactive'];
			$model->createdon=new CDbExpression('NOW()');
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		$this->performAjaxValidation($model);

		if(isset($_POST['Page']))
		{
			$model->attributes=$_POST['Page'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		if(Yii::app()->request->isPostRequest)
		{
			// we only allow deletion via POST request
			//$this->loadModel($id)->delete();
			  Page::model()->updateByPk($id,array('isdeleted'=>'yes'));
			// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
			if(!isset($_GET['ajax']))
				$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
		}
		else
			throw new CHttpException(400,'Invalid request. Please do not repeat this request again.');
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		/*$dataProvider=new CActiveDataProvider('Page');
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));*/
		
		// page size drop down changed
		if (isset($_GET['pageSize'])) {
			Yii::app()->user->setState('pageSize',(int)$_GET['pageSize']);
			unset($_GET['pageSize']);  // would interfere with pager and repetitive page size change
		}
        $model=new Page('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Page']))
			$model->attributes=$_GET['Page'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new Page('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Page']))
			$model->attributes=$_GET['Page'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer the ID of the model to be loaded
	 */
	public function loadModel($id)
	{
		$model=Page::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param CModel the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='page-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
	
	public function actionMultipleoperation()
	{
		$fetchIdarr=array();
		$fetchIdStr='';
		$operation=(isset($_POST['operation']) && $_POST['operation']!='') ? $_POST['operation'] : '';
		
		if(isset($_POST['chk']) && count($_POST['chk'])>0) {
				
			foreach($_POST['chk'] as $val) {
					$fetchIdarr[]=$val;
			}
			
			$fetchIdStr=implode(',',$fetchIdarr);
		}
	   
			
		if($operation=='Disable') {
			
		   /* $criteria = new CDbCriteria;
			$criteria->addInCondition( "id" , $fetchIdStr );
			User::model()->updateAll(array('isactive'=>'no'), $criteria);*/
			
		   if($fetchIdStr!='') {
				Page::model()->updateAll(array('isactive'=>'no'),'id IN ('.$fetchIdStr.')');
		   } 
		}
		
		if($operation=='Enable') {
			
		   if($fetchIdStr!='') {
				Page::model()->updateAll(array('isactive'=>'yes'),'id IN ('.$fetchIdStr.')');
		   }
		}
		
		
		if($operation=='Delete') {
			
		   if($fetchIdStr!='') {
				Page::model()->updateAll(array('isdeleted'=>'yes'),'id IN ('.$fetchIdStr.')');
		   }
		}
		
		
	}
}

protected/modules/admin/controllers/UserController.php
<?php

class UserController extends MYAdminController{

	public $layout='main';
	public function actionView($id)
	{
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}
	public function actionCreate()
	{
		$model=new User;
        $model->isactive='yes';
		
		// Uncomment the following line if AJAX validation is needed
		$this->performAjaxValidation($model);

		if(isset($_POST['User']))
		{
			$model->attributes=$_POST['User'];
			$model->isactive=$_POST['User']['isactive'];
			$model->password=md5($_POST['User']['password']);
			$model->createdon=new CDbExpression('NOW()');
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		$this->performAjaxValidation($model);

		if(isset($_POST['User']))
		{
			$model->attributes=$_POST['User'];
			if(trim($_POST['User']['password'])!='')  {
				$model->password=md5($_POST['User']['password']);
			}
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		if(Yii::app()->request->isPostRequest)
		{
			// we only allow deletion via POST request
			//$this->loadModel($id)->delete();
                        User::model()->updateByPk($id,array('isdeleted'=>'yes'));
			// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
			if(!isset($_GET['ajax']))
				$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
		}
		else
			throw new CHttpException(400,'Invalid request. Please do not repeat this request again.');
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		/*$dataProvider=new CActiveDataProvider('User');
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));*/
            
		// page size drop down changed
                if (isset($_GET['pageSize'])) {
                    Yii::app()->user->setState('pageSize',(int)$_GET['pageSize']);
                    unset($_GET['pageSize']);  // would interfere with pager and repetitive page size change
                }
                $model=new User('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['User']))
			$model->attributes=$_GET['User'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new User('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['User']))
			$model->attributes=$_GET['User'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer the ID of the model to be loaded
	 */
	public function loadModel($id)
	{
		$model=User::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param CModel the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='user-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
        
        public function actionMultipleoperation()
        {
            $fetchIdarr=array();
            $fetchIdStr='';
            $operation=(isset($_POST['operation']) && $_POST['operation']!='') ? $_POST['operation'] : '';
            
            if(isset($_POST['chk']) && count($_POST['chk'])>0) {
                    
                foreach($_POST['chk'] as $val) {
                        $fetchIdarr[]=$val;
                }
                
                $fetchIdStr=implode(',',$fetchIdarr);
            }
           
                
            if($operation=='Disable') {
                
               /* $criteria = new CDbCriteria;
                $criteria->addInCondition( "id" , $fetchIdStr );
                User::model()->updateAll(array('isactive'=>'no'), $criteria);*/
                
               if($fetchIdStr!='') {
                    User::model()->updateAll(array('isactive'=>'no'),'id IN ('.$fetchIdStr.')');
               } 
            }
            
            if($operation=='Enable') {
                
               if($fetchIdStr!='') {
                    User::model()->updateAll(array('isactive'=>'yes'),'id IN ('.$fetchIdStr.')');
               }
            }
            
            
            if($operation=='Delete') {
                
               if($fetchIdStr!='') {
                    User::model()->updateAll(array('isdeleted'=>'yes'),'id IN ('.$fetchIdStr.')');
               }
            }
            
            
        }
        
    
}

protected/modules/admin/views/layouts/column1.php
<?php $this->beginContent('//layouts/main'); ?>
<div id="content">
	<?php echo $content; ?>
</div><!-- content -->
<?php $this->endContent(); ?>

protected/modules/admin/views/layouts/column2.php
<?php $this->beginContent('//layouts/main'); ?>
<div class="span-19">
	<div id="content">
		<?php echo $content; ?>
	</div><!-- content -->
</div>
<div class="span-5 last">
	<div id="sidebar">
	<?php
		$this->beginWidget('zii.widgets.CPortlet', array(
			'title'=>'Operations',
		));
		$this->widget('zii.widgets.CMenu', array(
			'items'=>$this->menu,
			'htmlOptions'=>array('class'=>'operations'),
		));
		$this->endWidget();
	?>
	</div><!-- sidebar -->
</div>
<?php $this->endContent(); ?>

protected/modules/admin/views/layouts/layout_login_admin.php
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
        <link rel="shortcut icon" href="<?php echo Yii::app()->baseUrl; ?>/images/uploads/favicon.ico" />
		 <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
          <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
        <![endif]-->
        <title><?php echo CHtml::encode($this->pageTitle); ?> </title>
    </head>
	    <body class="bg-black">
        <?php echo $content; ?> 
    </body>
</html>

protected/modules/admin/views/layouts/xxmain.php
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="language" content="en" />
    <link href='http://fonts.googleapis.com/css?family=Droid+Sans:400,700' rel='stylesheet'>
    <?php Yii::app()->clientScript->registerCssFile( Yii::app()->themeManager->baseUrl . '/css/style.css'); ?>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
	<?php Yii::app()->clientScript->registerScriptFile( Yii::app()->themeManager->baseUrl . '/js/script.js', CClientScript::POS_HEAD); ?>

	<title><?php echo CHtml::encode($this->pageTitle); ?></title>
</head>

<body>

	<!-- TOP BAR -->
	<div id="top-bar">
		
		<?php if(Yii::app()->user->id != '') : ?>
        
        <div class="page-full-width cf">

			<ul id="nav" class="fl">
	
				<li class="v-sep"><a href="<?php echo Yii::app()->baseUrl; ?>" class="round button dark ic-left-arrow image-left">Go to website</a></li>
				<li class="v-sep"><a href="#" class="round button dark menu-user image-left">Logged in as <strong>admin</strong></a>
         <?php 
		 $this->widget('zii.widgets.CMenu',array(
				'items'=>array(
				array('label'=>Yii::t('adminglobal','My Profile'), 'url'=>array('user/view','id'=>Yii::app()->user->id)),
				array('label'=>Yii::t('adminglobal','Change Password'), 'url'=>array('user/update','id'=>Yii::app()->user->id)),
				array('label'=>Yii::t('adminglobal','Log out'), 'url'=>array('default/logout')),
			),
		)); 
		?>
				</li>
				<li class="v-sep"><a href="<?php echo $this->createUrl('default/logout'); ?>" class="round button dark menu-logoff image-left">Log out</a></li>
				<li><span class="round button dark">Welcome <?php echo ucwords(Yii::app()->user->adminfullname); ?></span></li>
			</ul> <!-- end nav -->

			
			<form action="#" method="POST" id="search-form" class="fr">
				<fieldset>
					<input type="text" id="search-keyword" class="round button dark ic-search image-right" placeholder="Search..." />
					<input type="hidden" value="SUBMIT" />
				</fieldset>
			</form>

		</div>
        
        <?php else: ?>
        <div class="page-full-width">
		
			<a href="<?php echo Yii::app()->baseUrl; ?>" target="_blank"  class="round button dark ic-left-arrow image-left ">Return to website</a>

		</div> 
        <?php endif; ?>
        <!-- end full-width -->	
	
	</div> <!-- end top-bar -->
        
        <!-- HEADER -->
	<div id="header-with-tabs">
		
		<div class="page-full-width cf">
			<?php if(Yii::app()->user->id == '') : ?>
			<div id="login-intro" class="fl">
			
				<h1><?php echo CHtml::encode($this->pageHeading1); ?></h1>
				<h5><?php echo CHtml::encode($this->pageHeading2); ?></h5>
			
			</div> <!-- login-intro -->
			<?php else: ?>
            <ul id="tabs" class="fl">
				<li><?php echo CHtml::link('Dashboard',array('default/index'),($this->id=='default') ? array('class'=>'active-tab dashboard-tab') : array('class'=>'dashboard-tab')); ?></li>
			</ul>
            <?php endif; ?>
			<!-- Change this image to your own company's logo -->
			<!-- The logo will automatically be resized to 39px height. -->
			<a href="#" id="company-branding" class="fr"><img src="<?php echo Yii::app()->themeManager->baseUrl; ?>/images/company-logo.png" alt="CMS" /></a>
			
		</div> <!-- end full-width -->	

	</div> 
    
    <!-- end header -->

	<!--<div id="mainmenu">
		<?php /* $this->widget('zii.widgets.CMenu',array(
			'items'=>array(
				array('label'=>'Home', 'url'=>array('/site/index')),
				array('label'=>'About', 'url'=>array('/site/page', 'view'=>'about')),
				array('label'=>'Contact', 'url'=>array('/site/contact')),
				array('label'=>'Login', 'url'=>array('/site/login'), 'visible'=>Yii::app()->user->isGuest),
				array('label'=>'Logout ('.Yii::app()->user->name.')', 'url'=>array('/site/logout'), 'visible'=>!Yii::app()->user->isGuest)
			),
		)); */ ?>
	</div>--><!-- mainmenu -->
        
	
                
        <div id="content">
			<div class="page-full-width cf">
            <?php if(Yii::app()->user->id != '') : ?>
            <div class="side-menu fl">
				
				<h3>Side Menu</h3>
          <?php 
		 $this->widget('zii.widgets.CMenu',array(
				'items'=>array(
				array('label'=>'Manage Users', 'url'=>array('user/index'),'active'=>$this->id=='user'),
				array('label'=>'Manage Pages', 'url'=>array('page/index'),'active'=>$this->id=='page'),
				array('label'=>'Log out', 'url'=>array('default/logout')),
			),
		)); 
		?>
				
			</div> <!-- end side-menu -->
            
            <div class="side-content fr">
            
			<?php //if(isset($this->breadcrumbs)):?>
			<?php //$this->widget('zii.widgets.CBreadcrumbs',
					 //array('links'=>$this->breadcrumbs,
				//)); ?><!-- breadcrumbs -->
			<?php //endif?>
            
            <?php endif; ?>
			<?php echo $content; ?>
            <?php if(Yii::app()->user->id != '') : ?>
            </div>
            <?php endif; ?>
            </div>
        </div>
	<div class="clear"></div>

	<!-- FOOTER -->
	<div id="footer">

		<p>&copy; Copyright 2012  CMS. All rights reserved.</p>
		<p><strong>SimpleAdmin</strong> theme</p>
	
	</div> <!-- end footer -->
</body>
</html>