protected/modules/admin/controllers/GoodsbrandController.php
<?php
class GoodsbrandController extends MYAdminController{
public $layout='//layouts/column2';

public function filters() {
        return array(
            //'accessControl', 
            'rights',
        );
    }
public function actionView($id)
{
$this->render('view',array(
'model'=>$this->loadModel($id),
));
}

/**
* Creates a new model.
* If creation is successful, the browser will be redirected to the 'view' page.
*/
public function actionCreate()
{
$model=new Goodsbrand;

// Uncomment the following line if AJAX validation is needed
// $this->performAjaxValidation($model);

if(isset($_POST['Goodsbrand']))
{
$model->attributes=$_POST['Goodsbrand'];
if($model->save())
$this->redirect(array('view','id'=>$model->id));
}

$this->render('create',array(
'model'=>$model,
));
}

/**
* Updates a particular model.
* If update is successful, the browser will be redirected to the 'view' page.
* @param integer $id the ID of the model to be updated
*/
public function actionUpdate($id)
{
$model=$this->loadModel($id);

// Uncomment the following line if AJAX validation is needed
// $this->performAjaxValidation($model);

if(isset($_POST['Goodsbrand']))
{
$model->attributes=$_POST['Goodsbrand'];
if($model->save())
$this->redirect(array('view','id'=>$model->id));
}

$this->render('update',array(
'model'=>$model,
));
}

/**
* Deletes a particular model.
* If deletion is successful, the browser will be redirected to the 'admin' page.
* @param integer $id the ID of the model to be deleted
*/
public function actionDelete($id)
{
if(Yii::app()->request->isPostRequest)
{
// we only allow deletion via POST request
$this->loadModel($id)->delete();

// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
if(!isset($_GET['ajax']))
$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
}
else
throw new CHttpException(400,'Invalid request. Please do not repeat this request again.');
}

/**
* Lists all models.
*/
public function actionIndex()
{
$dataProvider=new CActiveDataProvider('Goodsbrand');
$this->render('index',array(
'dataProvider'=>$dataProvider,
));
}

/**
* Manages all models.
*/
public function actionAdmin()
{
$model=new Goodsbrand('search');
$model->unsetAttributes();  // clear any default values
if(isset($_GET['Goodsbrand']))
$model->attributes=$_GET['Goodsbrand'];

$this->render('admin',array(
'model'=>$model,
));
}

/**
* Returns the data model based on the primary key given in the GET variable.
* If the data model is not found, an HTTP exception will be raised.
* @param integer the ID of the model to be loaded
*/
public function loadModel($id)
{
$model=Goodsbrand::model()->findByPk($id);
if($model===null)
throw new CHttpException(404,'The requested page does not exist.');
return $model;
}

/**
* Performs the AJAX validation.
* @param CModel the model to be validated
*/
protected function performAjaxValidation($model)
{
if(isset($_POST['ajax']) && $_POST['ajax']==='goodsbrand-form')
{
echo CActiveForm::validate($model);
Yii::app()->end();
}
}
}

protected/modules/admin/views/goodsbrand/_form.php
<?php
$form = $this->beginWidget('booster.widgets.TbActiveForm', array(
    'id' => 'goodsbrand-form',
    'enableAjaxValidation' => false,
    'type' => 'horizontal',
    'htmlOptions' => array('class' => 'well',
        'enctype' => 'multipart/form-data')
        ));
?>
<?php
$mytrue = TRUE;
if (!$model->isNewRecord) {
    $mytrue = FALSE;
}
?>

<fieldset class="myfieldset">
    <?php
    if ($mytrue) {
        ?>
        <legend class="mylegend"><i class="glyphicon glyphicon-plus"></i>เพิ่มยี่ห้อสินค้า</legend>
        <?php
    } else {
        ?>
        <legend class="mylegend"><i class="glyphicon glyphicon-pencil"></i>แก้ไขยี่ห้อสินค้า&nbsp;<?= $model->name ?></legend>    
        <?php
    }
    ?>
    <div style="margin-left:270px;">
        <p class="help-block">โปรดกรอกข้อมูลให้ครบทุกช่อง<span class="required">    *</span> </p>
    </div>
    <?php echo $form->errorSummary($model); ?>
    <?php echo $form->textFieldGroup($model, 'name', array('widgetOptions' => array('htmlOptions' => array('style' => 'width:250px;')))); ?>
    <div class="form-actions" style="margin-left:280px;">
        <?php
        $this->widget('booster.widgets.TbButton', array(
            'buttonType' => 'submit',
            'context' => 'primary',
            'label' => $model->isNewRecord ? 'บันทึก' : 'แก้ไข',
        ));
        ?>
        <?php
        $this->widget('booster.widgets.TbButton', array(
            'buttonType' => 'reset', 'label' => 'ยกเลิก')
        );
        ?>
    </div>
</fieldset>
<?php $this->endWidget(); ?>

protected/modules/admin/views/goodsbrand/_search.php
<?php $form=$this->beginWidget('booster.widgets.TbActiveForm',array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>

		<?php echo $form->textFieldGroup($model,'id',array('widgetOptions'=>array('htmlOptions'=>array()))); ?>

		<?php echo $form->textAreaGroup($model,'name', array('widgetOptions'=>array('htmlOptions'=>array('rows'=>6, 'cols'=>50)))); ?>

	<div class="form-actions">
		<?php $this->widget('booster.widgets.TbButton', array(
			'buttonType' => 'submit',
			'context'=>'primary',
			'label'=>'Search',
		)); ?>
	</div>

<?php $this->endWidget(); ?>

protected/modules/admin/views/goodsbrand/_view.php
<div class="view">

		<b><?php echo CHtml::encode($data->getAttributeLabel('id')); ?>:</b>
	<?php echo CHtml::link(CHtml::encode($data->id),array('view','id'=>$data->id)); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('name')); ?>:</b>
	<?php echo CHtml::encode($data->name); ?>
	<br />


</div>

protected/modules/admin/views/goodsbrand/admin.php
<?php
$this->breadcrumbs=array(
	'Goodsbrands'=>array('index'),
	'Manage',
);

$this->menu=array(
array('label'=>'List Goodsbrand','url'=>array('index')),
array('label'=>'Create Goodsbrand','url'=>array('create')),
);

Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
$('.search-form').toggle();
return false;
});
$('.search-form form').submit(function(){
$.fn.yiiGridView.update('goodsbrand-grid', {
data: $(this).serialize()
});
return false;
});
");
?>  
 <style type="text/css">
.text_center{
  text-align:center;
}
</style>
<div class="well">
    <h3>รายการยี่ห้อสินค้า</h3>
 <?php $form=$this->beginWidget('CActiveForm', array(
    'enableAjaxValidation'=>true,
)); ?>
<div style="margin-bottom:-46px;;" class="well">
<?php
echo CHtml::ajaxSubmitButton(
    $label = 'ลบข้อมูล', 
    array('goodsbrand/Ajaxupdate'), array('success' => 'reloadGrid'),
    $htmlOptions=array ('confirm'=>'ยืนยันการลบข้อมูล','class' => 'btn btn-danger')
    );
?>&nbsp;
<?php echo CHtml::link('เพิ่มข้อมูล',array('goodsbrand/create'),array('class'=>'btn btn-info')); ?>  
</div>
<?php 
$alert = 'ยืนยันการลบข้อมูล !';
$this->widget('booster.widgets.TbGridView',array(
'id'=>'goodsbrand-grid',
'type' => 'striped bordered',    
'dataProvider'=>$model->search(),
'filter'=>$model,
'selectableRows'=>3,    
'columns'=>array(
      array(
            'id' => 'id',
            'class' => 'CCheckBoxColumn', 
        ),
     'name',
        array('header' => '<span style="color:#428bca;">ดำเนินการ</span>',
           'class' => 'booster.widgets.TbButtonColumn',
            'template' => '{delete}{update}', //    'template'=>'{add} {list} {update} {print_act}',
            'buttons' => array(
                'update' => array(
                    'label' => 'แก้ไข',
                    'icon' => 'fa fa-pencil-square-o',
                    'url' => 'Yii::app()->controller->createUrl("goodsbrand/update", array("id"=>$data->id))',
                    'options' => array(
                        'class' => 'btn btn-small btn-warning', 'style' => 'margin:5px;',
                    ),
                ),
            'delete'=> array(
                    'url' => 'Yii::app()->controller->createUrl("goodsbrand/delete", array("id"=>$data->id))',
                    'label' => 'ลบ',
                   // 'icon' => 'fa fa-times',
                    'options' => array(// this is the 'html' array but we specify the 'ajax' element
                        'confirm' => $alert,
                        'class' => 'btn btn-small btn-danger',
                         'ajax' => array(
                            'type' => 'POST',
                            'url' => "js:$(this).attr('href')", // ajax post will use 'url' specified above
                            'success' => 'function(data){
                                if(data == 1){ 
                                 alert("ลบข้อมูลเรียบร้อยแล้วค่ะ !"); 
                                  $.fn.yiiGridView.update("goodsbrand-grid");
                                   return false;
                                }else if(data == 2){
                                 alert("คุณต้องลบข้อมูลผู้สมัครที่ลงทะเบียนไว้ก่อนค่ะ");
                                 window.location="index.php?r=admin/goodsbrand/admin";
                                 return false;
                                }else{
                                 alert("การลบข้อมูล error !"); 
                                //   $.fn.yiiGridView.update("goodsbrand-grid");
                                 return false;
                                }
                            }',
                        ),
                    ),
                ), 
            ),
            'htmlOptions' => array(
                'style' => 'width: 200px;', 'class' => 'text_center'
            ),
        )
),
)); ?>
</div>
<script>
function reloadGrid(data) {
    $.fn.yiiGridView.update('goodsbrand-grid');
}
</script>
<?php $this->endWidget(); ?>

protected/modules/admin/views/goodsbrand/create.php
<?php
$this->breadcrumbs=array(
	'Goodsbrands'=>array('index'),
	'Create',
);

$this->menu=array(
array('label'=>'List Goodsbrand','url'=>array('index')),
array('label'=>'Manage Goodsbrand','url'=>array('admin')),
);
?> 

<?php echo $this->renderPartial('_form', array('model'=>$model)); ?>

protected/modules/admin/views/goodsbrand/index.php
<?php
$this->breadcrumbs=array(
	'Goodsbrands',
);

$this->menu=array(
array('label'=>'Create Goodsbrand','url'=>array('create')),
array('label'=>'Manage Goodsbrand','url'=>array('admin')),
);
?>

<h1>Goodsbrands</h1>

<?php $this->widget('booster.widgets.TbListView',array(
'dataProvider'=>$dataProvider,
'itemView'=>'_view',
)); ?>

protected/modules/admin/views/goodsbrand/update.php
<?php
$this->breadcrumbs=array(
	'Goodsbrands'=>array('index'),
	$model->name=>array('view','id'=>$model->id),
	'Update',
);

	$this->menu=array(
	array('label'=>'List Goodsbrand','url'=>array('index')),
	array('label'=>'Create Goodsbrand','url'=>array('create')),
	array('label'=>'View Goodsbrand','url'=>array('view','id'=>$model->id)),
	array('label'=>'Manage Goodsbrand','url'=>array('admin')),
	);
	?> 

<?php echo $this->renderPartial('_form',array('model'=>$model)); ?>

protected/modules/admin/views/goodsbrand/view.php
<?php
$this->breadcrumbs=array(
	'Goodsbrands'=>array('index'),
	$model->name,
);

$this->menu=array(
array('label'=>'List Goodsbrand','url'=>array('index')),
array('label'=>'Create Goodsbrand','url'=>array('create')),
array('label'=>'Update Goodsbrand','url'=>array('update','id'=>$model->id)),
array('label'=>'Delete Goodsbrand','url'=>'#','linkOptions'=>array('submit'=>array('delete','id'=>$model->id),'confirm'=>'Are you sure you want to delete this item?')),
array('label'=>'Manage Goodsbrand','url'=>array('admin')),
);
?>

<h1>View Goodsbrand #<?php echo $model->id; ?></h1>

<?php $this->widget('booster.widgets.TbDetailView',array(
'data'=>$model,
'attributes'=>array(
		'id',
		'name',
),
)); ?>